"""Push LoRA adapter lên HF model repo + model card. HF_TOKEN từ env."""
import argparse
import os

from dotenv import load_dotenv

load_dotenv()
ap = argparse.ArgumentParser()
ap.add_argument("--adapter", required=True)
ap.add_argument("--repo", required=True)
ap.add_argument("--acc", default="")
a = ap.parse_args()

t = os.getenv("HF_TOKEN", "").encode("ascii", "ignore").decode().strip()
from huggingface_hub import HfApi

api = HfApi(token=t)
api.create_repo(a.repo, repo_type="model", exist_ok=True)

card = f"""---
license: mit
language:
- vi
base_model: Qwen/Qwen3-4B-Instruct-2507
tags:
- math
- vietnamese
- lora
- gsm8k
---

# Qwen3-4B — Vietnamese GSM8K (Agentic Self-Instruct)

LoRA adapter for `Qwen/Qwen3-4B-Instruct-2507`, fine-tuned on the
[vi-gsm8k-agentic dataset](https://huggingface.co/datasets/vuongtsc/vi-gsm8k-agentic) —
native Vietnamese grade-school math generated by an agentic self-instruct pipeline
(beats machine-translated data).

{a.acc}

- **Code:** https://github.com/loversky02/vi-gsm8k-agentic
- **Dataset:** https://huggingface.co/datasets/vuongtsc/vi-gsm8k-agentic
- **License:** MIT
"""
with open(os.path.join(a.adapter, "README.md"), "w", encoding="utf-8") as f:
    f.write(card)

api.upload_folder(folder_path=a.adapter, repo_id=a.repo, repo_type="model")
print(f"✓ pushed -> https://huggingface.co/{a.repo}")
